### ISSUE TITLE
3.0.1 test_highlight fails

### ISSUE THREAD

**Issue by dvzrv** [notanumber/xapian-haystack#215]
Hi! When trying to package 3.0.1 for Arch Linux I ran into issues with `test_highlight` which seems to generate one newline character too many:

```
======================================================================
FAIL: test_highlight (test_haystack.xapian_tests.tests.test_backend.BackendFeaturesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-xapian-haystack/src/django-haystack-3.1.1/test_haystack/xapian_tests/tests/test_backend.py", line 478, in test_highlight
    self.assertEqual([result.highlighted['text'] for result in results],
AssertionError: Lists differ: ['<em>indexed</em>!\n1', '<em>indexed</em>!\n2', '<em>indexed</em>!\n3'] != ['<em>indexed</em>!\n1\n', '<em>indexed</em>!\n2\n', '<em>indexed</em>!\n3\n']

First differing element 0:
'<em>indexed</em>!\n1'
'<em>indexed</em>!\n1\n'

- ['<em>indexed</em>!\n1', '<em>indexed</em>!\n2', '<em>indexed</em>!\n3']
+ ['<em>indexed</em>!\n1\n', '<em>indexed</em>!\n2\n', '<em>indexed</em>!\n3\n']
?                       ++                        ++                        ++


----------------------------------------------------------------------
Ran 110 tests in 0.545s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

This is using xapian-haystack 3.0.1 and django-haystack 3.1.1.

**Comment by asedeno** [comment]
xapian-haystack's tests run against django-haystack's master branch, not a particular released version.
Since django-haystack v3.1.1 was released, this was committed: https://github.com/django-haystack/django-haystack/commit/2782c063d75e02eef5e82be95b18fe5196139f36
While switching to run the test suite using GitHub Actions, I [adjusted our tests](https://github.com/notanumber/xapian-haystack/commit/20af9d214e73224a84d40629f121a196d133ed76#diff-e533cf71b5e9a07165741fa1267104f292d91003c06373f7a2a783315d04bd61R486) to match so they would also pass.

You may want to locally revert that one line change in `tests/xapian_tests/tests/test_backend.py` for your package for now.

**Comment by claudep** [comment]
@asedeno, can we now close this issue or is anything else expected?

**Comment by asedeno** [comment]
@claudep I don't know that anything else is expected. I can't close issues myself though.

**Comment by claudep** [comment]
@notanumber, @jorgecarleitao, would it be possible to grant some more permissions to @asedeno, please?

**Comment by notanumber** [comment]
@claudep do you have access to settings and collaborators? It looks like you're setup as a collaborator on this so I **think** you can add others. If not, I can add @asedeno as a collaborator as well if that works.

**Comment by claudep** [comment]
No, I don't have access to settings at all.

**Comment by notanumber** [comment]
No worries. I've sent them an invite to become a collaborator

**Comment by claudep** [comment]
Awesome, thanks a lot!

**Comment by notanumber** [comment]
It's all good. I'm just happy to see someone take up the reigns on the project. Don't want to see it whither away and die!
